version: '3.8'

services:
  # Service pour le développement
  memory-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0
    container_name: memory-app-dev

  # Service pour la production
  memory-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    container_name: memory-app-prod
    profiles:
      - production

  # Service Nginx standalone (alternative)
  memory-nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:80"
    container_name: memory-app-nginx
    profiles:
      - nginx
